GET localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "uje"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "todo": "test"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 1
}
